# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5e32fa50d065ef19be881e828b1578570c2a85d52adedae659e8fa27e3f5bafe7b47841cd3325d11f8e5b0a67d64d331f4375f103436bb96beb540efd6a08dc0

test:
  secret_key_base: 1382fd9a8cb027883f2691bf8598026b5522a6954fd6fc04a6f7a679f754122553ec28e9014d35d682092a7e7c2b2781486281fd72df6188dfaa9048cd058ce4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
